include: package:pedantic_mono/analysis_options.yaml
analyzer:
  exclude:
    - lib/l10n/messages_*.dart
    - ios/**
    - android/**
linter:
  rules:
    sort_pub_dependencies: false
    use_build_context_synchronously: false
    lines_longer_than_80_chars: false